version: "3.8"

services:

  smartcampus-mysql:
    image: mysql:8.4
    container_name: smartcampus-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 120s

    volumes:
      - smartcampus-mysql-data:/var/lib/mysql
      # Se apunta a la carpeta mysql-init dentro del backend
      - ./MontessoriSystem/mysql-init:/docker-entrypoint-initdb.d

    networks:
      - smartcampus-network


  smartcampusapi:
    build:
      context: ./MontessoriSystem
      dockerfile: Dockerfile
    image: smartcampusapi:latest
    container_name: smartcampus-container
    restart: unless-stopped

    depends_on:
      smartcampus-mysql:
        condition: service_healthy

    # Nota: Ya no es necesario exponer el puerto 8086 externamente, 
    # ya que Nginx (el frontend) actúa como proxy inverso en el puerto 80.
    # Descomenta las siguientes líneas si necesitas acceder al backend directamente por su puerto original.
    # ports:
    #   - "8086:80"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80

      SecurityConnection: ${SECURITY_CONNECTION}
      IdentityConnection: ${IDENTITY_CONNECTION}
      DefaultConnection: ${DEFAULT_CONNECTION}
      URL_Send_Forgot_Password: ${URL_SEND_FORGOT_PASSWORD}

    volumes:
      - smartcampus-DocumentStudent:/app/Files/DocumentStudent
      - smartcampus-FileUser:/app/Files/FileUser/User
      - smartcampus-Suject:/app/Files/FileUser/Suject
      - smartcampus-Students:/app/Files/FileUser/Students
      - smartcampus-Room:/app/Files/FileUser/Room
      - smartcampus-EducantionalInstitution:/app/Files/FileUser/EducantionalInstitution

    networks:
      - smartcampus-network


  smartstudentfrontend:
    build:
      context: ./Smart-Student-React
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=
    image: smartstudentfrontend:latest
    container_name: smartstudent-frontend
    restart: unless-stopped

    depends_on:
      - smartcampusapi


    networks:
      - smartcampus-network


networks:
  smartcampus-network:
    driver: bridge


volumes:
  smartcampus-mysql-data:
  smartcampus-DocumentStudent:
  smartcampus-FileUser:
  smartcampus-Suject:
  smartcampus-Students:
  smartcampus-Room:
  smartcampus-EducantionalInstitution:
