// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MontessoriSystem.Infrastructure.Persistence.Contexts;

#nullable disable

namespace MontessoriSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241125184753_Adding EvaluationsPeriodWithCalification")]
    partial class AddingEvaluationsPeriodWithCalification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.AchievementIndicators", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AssociatedGrades")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AchievementIndicators", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoAdjunto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("bytesAdjunto")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdTipoAdjunto");

                    b.ToTable("Adjunto", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int?>("IdSuject")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAbsent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsDelay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsExcuse")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Observation")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdRoom");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdSuject");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("IdUserCreator")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AcademicResolution")
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EducationalRegistry")
                        .HasColumnType("longtext");

                    b.Property<string>("IdCordinator")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("int");

                    b.Property<int?>("IdProvinceDom")
                        .HasColumnType("int");

                    b.Property<string>("IdRector")
                        .HasColumnType("longtext");

                    b.Property<string>("IdSecretary")
                        .HasColumnType("longtext");

                    b.Property<string>("IdUser")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsMainSchool")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Regional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlLogo")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAssignmentId")
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartment");

                    b.HasIndex("IdProvinceDom");

                    b.ToTable("EducationalInstitution", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EducationalLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EducationalLevel", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EvaluationsPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GradeStudent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdAchievementIndicator")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdStudent");

                    b.ToTable("EvaluationsPeriod", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EvaluationsPeriodWithCalification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Calification")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("GradeStudent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdAchievementIndicator")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("EvaluationsPeriodWithCalification", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdEducationalInsti")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdEducationalInsti");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.GroupCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdRoom");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.GroupGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupGrade", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.InitData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("Ready")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("InitData", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.InstitutionalCenterUsers", b =>
                {
                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CenterId", "UserId");

                    b.ToTable("InstitutionalCenterUsers", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MaritalStatus", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Nationality", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.ObservationCommentEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdStudent");

                    b.ToTable("ObservationCommentEvaluation");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Professions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Profession", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.ProvinceDom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProvinceDom", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.RelationshipPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RelationshipPerson", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdEducationalInsti")
                        .HasColumnType("int");

                    b.Property<string>("IdTeacherLead")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdTypeRegisters")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TypeRegisterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEducationalInsti");

                    b.HasIndex("TypeRegisterId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.RoomSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("FinishDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int>("IdSubject")
                        .HasColumnType("int");

                    b.Property<string>("IdTeacher")
                        .HasColumnType("longtext");

                    b.Property<string>("InitDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdRoom");

                    b.ToTable("RoomSchedule", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.RoomTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int>("IdSuject")
                        .HasColumnType("int");

                    b.Property<string>("IdTeacher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("IdRoom");

                    b.HasIndex("IdSuject");

                    b.ToTable("RoomTeacher", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Specializations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Specializations", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AgesSiblings")
                        .HasColumnType("longtext");

                    b.Property<string>("Book")
                        .HasColumnType("longtext");

                    b.Property<string>("BornDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("CarriedPreprimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Direction")
                        .HasColumnType("longtext");

                    b.Property<string>("DiseasesAllergic")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorPediatrician")
                        .HasColumnType("longtext");

                    b.Property<int?>("EducationalInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EmergencyPerson")
                        .HasColumnType("longtext");

                    b.Property<string>("EmergencyTel")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Folio")
                        .HasColumnType("longtext");

                    b.Property<string>("IdFather")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdGrade")
                        .HasColumnType("int");

                    b.Property<int?>("IdInstitu")
                        .HasColumnType("int");

                    b.Property<string>("IdMother")
                        .HasColumnType("longtext");

                    b.Property<int?>("IdNacionality")
                        .HasColumnType("int");

                    b.Property<int?>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int?>("IdTypeRegister")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MedicinesUse")
                        .HasColumnType("longtext");

                    b.Property<string>("NEAE")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NumberSiblings")
                        .HasColumnType("int");

                    b.Property<int?>("PlaceBetweenSiblings")
                        .HasColumnType("int");

                    b.Property<string>("RelationPersonLiveWith")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext");

                    b.Property<string>("TelFather")
                        .HasColumnType("longtext");

                    b.Property<string>("TelMother")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImg")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EducationalInstitutionId");

                    b.HasIndex("IdGrade");

                    b.HasIndex("IdRoom");

                    b.HasIndex("IdTypeRegister");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Suject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdEducationalInsti")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdEducationalInsti");

                    b.ToTable("Suject", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.TeachingPeriods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateFinish")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateInit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdEducationalInsti")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdEducationalInsti");

                    b.ToTable("TeachingPeriods", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.TipoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoAdjunto", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.TitlesAchieved", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TitlesAchieved", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.TypeRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TypeRegister", (string)null);
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Adjunto", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Student", "Student")
                        .WithMany("Adjuntos")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.TipoAdjunto", "TipoAdjunto")
                        .WithMany("Adjuntos")
                        .HasForeignKey("IdTipoAdjunto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TipoAdjunto");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Room", "Room")
                        .WithMany("Attendance")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Student", "Student")
                        .WithMany("Attendance")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Suject", "Suject")
                        .WithMany("Attendance")
                        .HasForeignKey("IdSuject")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");

                    b.Navigation("Student");

                    b.Navigation("Suject");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Department", "Department")
                        .WithMany("Institutions")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.ProvinceDom", "ProvinceDom")
                        .WithMany("Institutions")
                        .HasForeignKey("IdProvinceDom")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("ProvinceDom");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EvaluationsPeriod", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Student", "Student")
                        .WithMany("EvaluationsPeriod")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EvaluationsPeriodWithCalification", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Grade", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", "EducationalInstitution")
                        .WithMany("Grade")
                        .HasForeignKey("IdEducationalInsti")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EducationalInstitution");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.GroupCenter", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Room", "Room")
                        .WithMany("GroupCenter")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.GroupGrade", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Grade", "Grade")
                        .WithMany("GroupGrade")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.GroupCenter", "GroupCenter")
                        .WithMany("GroupGrade")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("GroupCenter");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.InstitutionalCenterUsers", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", "EducationalInstitution")
                        .WithMany("InstitutionalCenterUsers")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalInstitution");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.ObservationCommentEvaluation", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Student", "Student")
                        .WithMany("ObservationCommentEvaluation")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Room", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", "EducationalInstitution")
                        .WithMany("Room")
                        .HasForeignKey("IdEducationalInsti")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.TypeRegister", null)
                        .WithMany("Room")
                        .HasForeignKey("TypeRegisterId");

                    b.Navigation("EducationalInstitution");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.RoomSchedule", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Room", "Room")
                        .WithMany("Schedules")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.RoomTeacher", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Grade", null)
                        .WithMany("RoomTeachers")
                        .HasForeignKey("GradeId");

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Room", "Room")
                        .WithMany("RoomTeachers")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Suject", "Suject")
                        .WithMany("RoomTeacher")
                        .HasForeignKey("IdSuject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Suject");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Student", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", "EducationalInstitution")
                        .WithMany("Student")
                        .HasForeignKey("EducationalInstitutionId");

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("IdGrade")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.Room", "Room")
                        .WithMany("Student")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MontessoriSystem.Core.Domain.Entities.TypeRegister", "TypeRegister")
                        .WithMany("Student")
                        .HasForeignKey("IdTypeRegister")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EducationalInstitution");

                    b.Navigation("Grade");

                    b.Navigation("Room");

                    b.Navigation("TypeRegister");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Suject", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", "EducationalInstitution")
                        .WithMany("Suject")
                        .HasForeignKey("IdEducationalInsti")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalInstitution");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.TeachingPeriods", b =>
                {
                    b.HasOne("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", "EducationalInstitution")
                        .WithMany("SelectivePeriod")
                        .HasForeignKey("IdEducationalInsti")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalInstitution");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Department", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.EducationalInstitution", b =>
                {
                    b.Navigation("Grade");

                    b.Navigation("InstitutionalCenterUsers");

                    b.Navigation("Room");

                    b.Navigation("SelectivePeriod");

                    b.Navigation("Student");

                    b.Navigation("Suject");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Grade", b =>
                {
                    b.Navigation("GroupGrade");

                    b.Navigation("RoomTeachers");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.GroupCenter", b =>
                {
                    b.Navigation("GroupGrade");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.ProvinceDom", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Room", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("GroupCenter");

                    b.Navigation("RoomTeachers");

                    b.Navigation("Schedules");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Student", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Attendance");

                    b.Navigation("EvaluationsPeriod");

                    b.Navigation("ObservationCommentEvaluation");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.Suject", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("RoomTeacher");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.TipoAdjunto", b =>
                {
                    b.Navigation("Adjuntos");
                });

            modelBuilder.Entity("MontessoriSystem.Core.Domain.Entities.TypeRegister", b =>
                {
                    b.Navigation("Room");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
